# Generated by Django 5.1.2 on 2024-12-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0006_candidate_likes_alter_candidatelike_candidate'),
        ('organization', '0015_remove_organization_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ManyToManyField(to='candidate.candidate')),
                ('project', models.ManyToManyField(to='organization.projects')),
            ],
        ),
    ]
