# Generated by Django 5.1.4 on 2024-12-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0001_initial'),
        ('organization', '0015_remove_organization_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organization.projects'),
            preserve_default=False,
        ),
    ]
