# Generated by Django 5.1.2 on 2024-12-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidate_likes_alter_candidatelike_candidate'),
        ('matchApp', '0001_initial'),
        ('organization', '0015_remove_organization_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='project',
            field=models.ManyToManyField(to='organization.projects'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='candidate',
        ),
        migrations.AddField(
            model_name='match',
            name='candidate',
            field=models.ManyToManyField(to='candidate.candidate'),
        ),
    ]
