# Generated by Django 5.1.2 on 2024-12-17 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_remove_candidate_likes_delete_candidatelike'),
        ('matchApp', '0001_initial'),
        ('organization', '0016_remove_projects_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='project',
        ),
        migrations.AddField(
            model_name='match',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='match',
            name='candidate',
        ),
        migrations.CreateModel(
            name='CandidateLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_likes', to='candidate.candidate')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_liked', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_liked', to='candidate.candidate')),
                ('organization', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='organization_likes', to='organization.organization')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
            preserve_default=False,
        ),
    ]
