# Generated by Django 5.1.2 on 2024-12-17 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0001_initial'),
        ('organization', '0016_alter_organization_profile_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches1', to='organization.organization'),
        ),
    ]
