# Generated by Django 5.1.2 on 2024-12-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_remove_candidate_likes_delete_candidatelike'),
        ('matchApp', '0002_match_project_remove_match_candidate_match_candidate'),
        ('organization', '0016_remove_projects_likes_delete_organizationlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_likes', to='candidate.candidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_liked', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_liked', to='candidate.candidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_likes', to='organization.organization')),
            ],
        ),
    ]
