# Generated by Django 5.1.2 on 2024-12-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchApp', '0002_match_project'),
        ('matchApp', '0002_remove_match_project_match_organization_and_more'),
    ]

    operations = [
    ]
