# Generated by Django 5.1.2 on 2024-12-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_remove_candidate_likes_delete_candidatelike'),
        ('matchApp', '0003_candidatelike_organizationlike'),
        ('organization', '0016_remove_projects_likes_delete_organizationlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='project',
        ),
        migrations.AddField(
            model_name='match',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='match',
            name='candidate',
        ),
        migrations.AddField(
            model_name='match',
            name='candidate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
            preserve_default=False,
        ),
    ]
