# Generated by Django 5.1.2 on 2024-12-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_remove_candidate_likes_delete_candidatelike'),
        ('matchApp', '0006_rename_superlike_candidatesuperlike_and_more'),
        ('organization', '0019_remove_organization_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatesuperlike',
            unique_together={('organization', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationsuperlike',
            unique_together={('organization', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='candidatesuperlike',
            index=models.Index(fields=['organization', 'candidate'], name='matchApp_ca_organiz_539ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsuperlike',
            index=models.Index(fields=['organization', 'candidate'], name='matchApp_or_organiz_520d22_idx'),
        ),
    ]
