# Generated by Django 5.1.2 on 2024-12-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_remove_candidate_likes_delete_candidatelike'),
        ('matchApp', '0007_alter_candidatesuperlike_unique_together_and_more'),
        ('organization', '0019_remove_organization_likes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidatesuperlike',
            name='matchApp_ca_organiz_539ebc_idx',
        ),
        migrations.RemoveIndex(
            model_name='organizationsuperlike',
            name='matchApp_or_organiz_520d22_idx',
        ),
        migrations.AlterUniqueTogether(
            name='candidatesuperlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='organizationsuperlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='candidatelike',
            unique_together={('organization', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationlike',
            unique_together={('organization', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='candidatelike',
            index=models.Index(fields=['organization', 'candidate'], name='matchApp_ca_organiz_747db1_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationlike',
            index=models.Index(fields=['organization', 'candidate'], name='matchApp_or_organiz_802b93_idx'),
        ),
    ]
