# Generated by Django 5.1.2 on 2024-12-12 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_completion',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
