# Generated by Django 5.1.2 on 2024-12-15 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidatelike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='likes',
            field=models.ManyToManyField(related_name='liked_candidates', through='candidate.CandidateLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidatelike',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_candidates', to='candidate.candidate'),
        ),
    ]
