# Generated by Django 5.1.2 on 2024-12-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidate_likes_alter_candidatelike_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='likes',
        ),
        migrations.DeleteModel(
            name='CandidateLike',
        ),
    ]
