# Generated by Django 5.1.2 on 2024-12-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_created_at_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
