# Generated by Django 5.1.2 on 2024-12-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
