# Generated by Django 5.1.2 on 2024-12-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_skill_organization_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='skills',
            field=models.ManyToManyField(to='organization.skill'),
        ),
    ]
