# Generated by Django 5.1.2 on 2024-12-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_organization_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='profile_completion',
            field=models.SmallIntegerField(default=10, max_length=100),
        ),
    ]
