# Generated by Django 5.1.2 on 2024-12-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_organization_profile_projects'),
        ('organization', '0013_organization_likes_and_more'),
    ]

    operations = [
    ]
