# Generated by Django 5.1.2 on 2024-12-16 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_merge_20241216_1206'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='organizationlike',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizationlike',
            name='projects',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='organization_likes', to='organization.projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(related_name='liked_organizations', through='organization.OrganizationLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
