# Generated by Django 5.1.2 on 2024-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_remove_organization_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='likes',
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_completion',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='OrganizationLike',
        ),
    ]
