# Generated by Django 5.1.2 on 2024-12-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_remove_organization_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='likes',
        ),
        migrations.DeleteModel(
            name='OrganizationLike',
        ),
    ]
