# Generated by Django 5.1.2 on 2024-12-17 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_alter_organization_profile_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='likes',
            field=models.ManyToManyField(related_name='liked_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
