# Generated by Django 5.1.2 on 2024-12-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_organization_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='likes',
        ),
    ]
